name: ogd-at-lab
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - numpy
  - cython
  - matplotlib
  - seaborn
  - pandas
  - geopandas
  - movingpandas
  - rasterio
  - hvplot
  - bokeh
  - proj
  - cartopy
  - geoviews
  - scikit-learn
  - geopy
  - panel
